{% set name = "KineticPredictorModel" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joegilkes/KineticPredictorModel/archive/v{{ version }}.tar.gz
  sha256: 5b56a8728ee13d097c08afd0ea0e411be2a1400fbaee70287cad11175ba38d99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy >=1.20
    - matplotlib-base >=3.5
    - pandas
    - scipy
    - seaborn
    - scikit-learn >=0.21
    - openbabel >=3.1
    - rdkit

test:
  imports:
    - KPM

about:
  summary: Ea prediction using molecular structure and energy
  home: https://github.com/idilismail/KineticPredictorModel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joegilkes
